{% set name = "enterprise" %}
{% set version = "3.0.0" %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    git_url: https://github.com/nanograv/enterprise.git
    # git_rev:
    git_depth: 1

build:
    number: 3

# test:
    # source_files:
    #     - tests/
    # commands:
    #     # run tests for enterprise here:
    #     # or we could make a test.sh script

requirements:

    host:
        - python =3.7
        - matplotlib
        - pandas
        - jupyter
        - notebook
        - h5py
        - basemap
        - astropy
        - ephem
        - mpi4py
        - conda-forge::suitesparse=5.7.2
        - conda-forge::healpy
        - conda-forge::scikit-sparse=0.4.4=py37h889afb3_1004
        - conda-forge::jplephem
        - aarondjohnson::libstempo
        - conda-forge::pint-pulsar
        - conda-forge::corner
        - aarondjohnson::ptmcmcsampler

    run:
        # check that each of these are actually necessary:
        - python =3.7
        - matplotlib
        - pandas
        - jupyter
        - notebook
        - h5py
        - basemap
        - astropy
        - ephem
        - mpi4py
        - conda-forge::suitesparse=5.7.2
        - conda-forge::healpy
        - conda-forge::scikit-sparse=0.4.4=py37h889afb3_1004
        - conda-forge::jplephem
        - aarondjohnson::libstempo
        - conda-forge::pint-pulsar
        - conda-forge::corner
        - aarondjohnson::ptmcmcsampler

